CREATE DATABASE IF NOT EXISTS calendar;
USE calendar;

DROP TABLE IF EXISTS tests;
DROP TABLE IF EXISTS events;

CREATE TABLE IF NOT EXISTS tests(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(255),
    PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS events(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    date1 DATE NOT NULL,
    date2 DATE,
    time1 TIME,
    time2 TIME,
    PRIMARY KEY(id)
);